language: php

php:
  - "7.1"

env:
  - WP_VERSION=4.9

services:
  - mysql

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer install

jobs:
  include:
    - stage: inspect
      script: ./vendor/bin/phing inspect
    - stage: test
      script: ./vendor/bin/phing tests:coverage

stages:
  - inspect
  - test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
